site_name: Node-RED AI Photo Booth Workshop
site_description: >-
  A workshop for creating an AI-infused photo booth application using Node-RED and TensorFlow.js
site_url: https://knolleary.github.io/node-red-workshop-photobooth/
site_author: Nick O'Leary
repo_name: knolleary/node-red-workshop-photobooth
repo_url: https://github.com/knolleary/node-red-workshop-photobooth
edit_uri: edit/main/docs/
theme:
    name: material
    custom_dir: theme/
    icon:
        logo: material/school
        repo: fontawesome/brands/github
use_directory_urls: false
plugins:
  - search
#  - with-pdf:
#      cover_subtitle: My subtitle
#      output_path: pdf/photoboothWorkshop.pdf
markdown_extensions:
  - attr_list
  - admonition
  - toc:
      permalink: true
      toc_depth: 3
extra_css:
    - css/extra.css
    - css/pdf-print.css
nav:
  - Home: index.md
  - 1 - Introduction:
    - Introduction: part1/README.md
  - 2 - Node-RED:
    - Introduction: part2/README.md
    - Install Node-RED: part2/install.md
    - Enabling Projects: part2/projects.md
    - Installing Nodes: part2/installing-nodes.md
  - 3 - Node-RED Dashboard:
    - Introduction: part3/README.md
    - Create a dashboard: part3/create-dashboard.md
    - Adding controls: part3/adding-controls.md
  - 4 - TensorFlow:
    - Intro: part4/README.md
  - 5 - Creating a container:
    - Intro: part5/README.md
  - 6 - Summary:
    - Intro: part6/README.md
  - Additional:
    - Resources: RESOURCES.md
