site_name: Node-RED AI Photo Booth Workshop
site_description: >-
  A workshop for creating an AI-infused photo booth application using Node-RED and TensorFlow.js
site_url: https://knolleary.github.io/node-red-workshop-photobooth/
site_author: Nick O'Leary
repo_name: knolleary/node-red-workshop-photobooth
repo_url: https://github.com/knolleary/node-red-workshop-photobooth
edit_uri: edit/main/docs/
theme:
    name: material
    custom_dir: theme/
    icon:
        logo: material/school
        repo: fontawesome/brands/github
use_directory_urls: false
plugins:
  - search
  - with-pdf:
      cover_subtitle: NodeConf Remote 2020
      output_path: pdf/node-red-workshop-photobooth.pdf
      enabled_if_env: ENABLE_PDF_EXPORT
markdown_extensions:
  - attr_list
  - admonition
  - toc:
      permalink: true
      toc_depth: 3
extra_css:
    - css/extra.css
    - css/pdf-print.css
nav:
  - Introduction: index.md
  - 1 - Node-RED:
    - Introduction: part1/README.md
    - Install Node-RED: part1/install.md
    - Enabling Projects: part1/projects.md
    - Installing Nodes: part1/installing-nodes.md
    - Creating a Flow: part1/create-flow.md
    - Committing Changes: part1/commit-changes.md
  - 2 - Node-RED Dashboard:
    - Introduction: part2/README.md
    - Create a dashboard: part2/create-dashboard.md
    - Adding controls: part2/adding-controls.md
  - 3 - TensorFlow:
    - Introduction: part3/README.md
    - TensorFlow in Node-RED: part3/adding-tf.md
    - Displaying detected objects: part3/display-objects.md
    - Selecting objects to display: part3/select-objects.md
  - 4 - Containerization:
    - Introduction: part4/README.md
    - Package file: part4/package.md
    - Settings file: part4/settings.md
    - Dockerfile: part4/dockerfile.md
  - 5 - Summary:
    - Intro: part5/README.md
  - Additional:
    - Resources: RESOURCES.md
